/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib.application;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;


public class AndraAgent extends javax.swing.JFrame {
    
    private ArrayList<String> agentID;
    private static InfDB idb;
    private static String id;
    private ArrayList<String> omrade;
    

    /**
     * Creates new form AndraAgent
     */
    public AndraAgent(InfDB idb, String id) {
        initComponents();
        this.idb = idb;
        this.id = id;
        
        try{
            omrade = idb.fetchColumn("SELECT Benamning FROM Omrade");
            omrade.forEach(ansvararForOmrade -> {
                    boxNyttOmrade.addItem(ansvararForOmrade);
                                                });
    
            agentID = idb.fetchColumn("SELECT Agent_ID FROM Agent ORDER BY Agent_ID ASC");
            agentID.forEach(idNr -> {
                boxIDNummer.addItem(idNr);
                                    });          
            }
        
            catch(InfException e){
                    JOptionPane.showMessageDialog(null, "Något gick fel. Vänligen försök igen");
                                 }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxIDNummer = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNyttNamn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNyttTelenr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNyttLosenord = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        boxNyttOmrade = new javax.swing.JComboBox<>();
        lblMIB = new javax.swing.JLabel();
        godkännKnapp = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        goBack = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boxIDNummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxIDNummerActionPerformed(evt);
            }
        });
        getContentPane().add(boxIDNummer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 171, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Välj agent att hantera");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 120, 20));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Namn");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 120, 20));
        getContentPane().add(txtNyttNamn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 171, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Telefonnummer");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 120, 20));
        getContentPane().add(txtNyttTelenr, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 171, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Lösenord");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 120, 20));
        getContentPane().add(txtNyttLosenord, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 171, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Ansvarig för område");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 120, 20));

        getContentPane().add(boxNyttOmrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 171, -1));

        lblMIB.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblMIB.setForeground(new java.awt.Color(255, 255, 255));
        lblMIB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMIB.setText("Hantera agent");
        lblMIB.setToolTipText("");
        getContentPane().add(lblMIB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 740, -1));

        godkännKnapp.setBackground(new java.awt.Color(0, 0, 0));
        godkännKnapp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));
        godkännKnapp.setForeground(new java.awt.Color(102, 153, 255));
        godkännKnapp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        godkännKnapp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                godkännKnappMouseReleased(evt);
            }
        });
        godkännKnapp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/accept.png"))); // NOI18N
        godkännKnapp.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 20, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 153, 255));
        jLabel11.setText("Godkänn");
        godkännKnapp.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 70, 30));

        getContentPane().add(godkännKnapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 110, 30));

        goBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/GoBack.png"))); // NOI18N
        goBack.setToolTipText("");
        goBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                goBackMouseReleased(evt);
            }
        });
        getContentPane().add(goBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/spaceBlue.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boxIDNummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxIDNummerActionPerformed
        
        try{
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
            String id = (String)boxIDNummer.getSelectedItem();
            String namn = idb.fetchSingle("SELECT Namn FROM Agent WHERE Agent_ID =" + id);
            String telefon = idb.fetchSingle("SELECT Telefon FROM Agent WHERE Agent_ID=" + id);
            String losenord = idb.fetchSingle("SELECT Losenord FROM Agent WHERE Agent_ID=" + id);
            int ansvarOmrade = Integer.parseInt(idb.fetchSingle("SELECT Omrade FROM Agent WHERE Agent_ID=" + id));
            String ansvararForOmrade = idb.fetchSingle("SELECT Benamning FROM Omrade WHERE Omrades_ID=" + ansvarOmrade);
            boxNyttOmrade.setSelectedItem(ansvararForOmrade);
            
            
            txtNyttNamn.setText(namn);
            txtNyttTelenr.setText(telefon);
            txtNyttLosenord.setText(losenord);
            
        }
            catch(InfException e){}
        
   
    }//GEN-LAST:event_boxIDNummerActionPerformed

    private void godkännKnappMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_godkännKnappMouseReleased
        int valdAgent = Integer.parseInt((String)boxIDNummer.getSelectedItem());
        
        
        if(Validering.txtFieldBegransad6(txtNyttLosenord) && Validering.txtFieldBegransad30(txtNyttTelenr) && Validering.txtFieldBegransad20(txtNyttNamn)){
        
            try{
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
            String namn = txtNyttNamn.getText();
            String telefon = txtNyttTelenr.getText();
            String losenord = txtNyttLosenord.getText();
            String valtOmrade = (String)boxNyttOmrade.getSelectedItem();  
            String omradesIDFraga = "SELECT Omrades_ID FROM Omrade WHERE Benamning ='" + valtOmrade + "'";
            String hamtaOmradesID = idb.fetchSingle(omradesIDFraga);
            int intOmradesID = Integer.parseInt(hamtaOmradesID);
            
            int svara = JOptionPane.showConfirmDialog(null, "Är du säker på att du vill genomföra dessa ändringar?", "Obs!", JOptionPane.YES_NO_OPTION);
            
                if(svara == JOptionPane.YES_OPTION){            
                    idb.update("UPDATE Agent SET Namn='" + namn + "'WHERE Agent_ID=" + valdAgent + "");
                    idb.update("UPDATE Agent SET Telefon='" + telefon + "'WHERE Agent_ID=" + valdAgent + "");
                    idb.update("UPDATE Agent SET Losenord='" + losenord + "'WHERE Agent_ID=" + valdAgent + "");
                    idb.update("UPDATE Agent SET Omrade='" + intOmradesID + "'WHERE Agent_ID=" + valdAgent + "");
            
                    JOptionPane.showMessageDialog(null, "Ändringarna har nu genomförts");
                                                    }
            
            }
                catch(InfException e){
                        JOptionPane.showMessageDialog(null, "Oj! Något gick fel");
                        System.out.println(e);
                                     }
        }
    }//GEN-LAST:event_godkännKnappMouseReleased

    private void goBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackMouseReleased
        new AdminHanteraAgent(idb, id).setVisible(true);
        dispose();
    }//GEN-LAST:event_goBackMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndraAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndraAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndraAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndraAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AndraAgent(idb, id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxIDNummer;
    private javax.swing.JComboBox<String> boxNyttOmrade;
    private javax.swing.JLabel goBack;
    private javax.swing.JPanel godkännKnapp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblMIB;
    private javax.swing.JTextField txtNyttLosenord;
    private javax.swing.JTextField txtNyttNamn;
    private javax.swing.JTextField txtNyttTelenr;
    // End of variables declaration//GEN-END:variables
}
