/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib.application;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author mathildabernebyhaeffner
 */
public class InfoRuta extends javax.swing.JFrame {
    private InfDB idb;
    private String id;

    /**
     * Creates new form InfoRuta
     */
    public InfoRuta(InfDB idb, String id) {
        initComponents();
        this.idb = idb;
        this.id = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        omradeschefKnapp = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        aliensOmradeKnapp = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextArea();
        goBack = new javax.swing.JLabel();
        lblMIB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        omradeschefKnapp.setBackground(new java.awt.Color(0, 0, 0));
        omradeschefKnapp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));
        omradeschefKnapp.setForeground(new java.awt.Color(102, 153, 255));
        omradeschefKnapp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        omradeschefKnapp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                omradeschefKnappMouseReleased(evt);
            }
        });
        omradeschefKnapp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/MiB Man.png"))); // NOI18N
        omradeschefKnapp.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 153, 255));
        jLabel3.setText("Se områdeschef");
        omradeschefKnapp.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 150, 80));

        getContentPane().add(omradeschefKnapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 260, 80));

        aliensOmradeKnapp.setBackground(new java.awt.Color(0, 0, 0));
        aliensOmradeKnapp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));
        aliensOmradeKnapp.setForeground(new java.awt.Color(102, 153, 255));
        aliensOmradeKnapp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aliensOmradeKnapp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                aliensOmradeKnappMouseReleased(evt);
            }
        });
        aliensOmradeKnapp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/omrade.png"))); // NOI18N
        aliensOmradeKnapp.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 17, 50, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setText("Aliens i närheten");
        aliensOmradeKnapp.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 150, 80));

        getContentPane().add(aliensOmradeKnapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 260, 80));

        txtInfo.setBackground(new java.awt.Color(0, 0, 0));
        txtInfo.setColumns(20);
        txtInfo.setForeground(new java.awt.Color(255, 255, 255));
        txtInfo.setRows(5);
        jScrollPane1.setViewportView(txtInfo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 290, 200));

        goBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/GoBack.png"))); // NOI18N
        goBack.setToolTipText("");
        goBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                goBackMouseReleased(evt);
            }
        });
        getContentPane().add(goBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblMIB.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblMIB.setForeground(new java.awt.Color(255, 255, 255));
        lblMIB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMIB.setText("Områdesinformation");
        lblMIB.setToolTipText("");
        getContentPane().add(lblMIB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 740, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/spaceBlue.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aliensOmradeKnappMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aliensOmradeKnappMouseReleased
        //Listar alla aliens som finns i närheten, tillsammans med information om dem
        
        txtInfo.selectAll();
        txtInfo.replaceSelection("");
        try {
            String omrade = idb.fetchSingle("SELECT Plats FROM Alien WHERE Alien_ID =" + id);
            ArrayList<HashMap<String,String>> allaAliens = idb.fetchRows("SELECT Telefon, Namn FROM Alien JOIN Plats ON Plats_ID = Plats JOIN Omrade ON Omrades_ID = Finns_I WHERE Plats_ID ='" + omrade + "'");
            for (HashMap<String, String> list : allaAliens) {                
                for(Map.Entry<String,String> lista : list.entrySet()){
                    String key = lista.getKey();
                    String value = lista.getValue();
                    if(key.equals("Telefon")){
                        txtInfo.insert("Telefon: " + value + "\n", 0);
                    }
                    else{
                        txtInfo.insert("Namn: " + value + "\n\n", 0);
                    }
                }
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
        }
    }//GEN-LAST:event_aliensOmradeKnappMouseReleased

    private void omradeschefKnappMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_omradeschefKnappMouseReleased
        //En metod som visar vem som är områdeschef i området en alien vistas i
        txtInfo.selectAll();
        txtInfo.replaceSelection("");
        try {
            HashMap<String,String> agent = idb.fetchRow("SELECT Agent.Namn, Agent.Telefon FROM Agent JOIN Omradeschef ON Omradeschef.Agent_ID = Agent.Agent_ID JOIN Alien ON Plats = Omradeschef.Omrade WHERE Alien_ID =" + id);
            for (String agentInfo  : agent.values()) {
                txtInfo.insert(agentInfo + "\n", 0);
                
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
        }
    }//GEN-LAST:event_omradeschefKnappMouseReleased

    private void goBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackMouseReleased
        AlienStartsida as = new AlienStartsida(idb, id);
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_goBackMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aliensOmradeKnapp;
    private javax.swing.JLabel goBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMIB;
    private javax.swing.JPanel omradeschefKnapp;
    private javax.swing.JTextArea txtInfo;
    // End of variables declaration//GEN-END:variables
}
