/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib.application;

import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
/**
 *
 * @author anton
 */
public class RegistreraUtrustning extends javax.swing.JFrame {

    private static InfDB idb;
    private static String id;
    private AgentMeny agentMeny;
    /**
     * Creates new form RegistreraUtrustning
     */
    public RegistreraUtrustning(InfDB idb, String id) {
        initComponents();
        this.idb = idb;
        this.id = id;
        utrustningDetalj.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        utrustningNamn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        godkann = new javax.swing.JButton();
        avbryt = new javax.swing.JButton();
        arVapen = new javax.swing.JCheckBox();
        arKomm = new javax.swing.JCheckBox();
        arTeknik = new javax.swing.JCheckBox();
        labelFranBox = new javax.swing.JLabel();
        utrustningDetalj = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Vilken utrustning vill du registrera?");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Namnge den nya utrustningen");

        godkann.setText("Godkänn");
        godkann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                godkannActionPerformed(evt);
            }
        });

        avbryt.setText("Avbryt");
        avbryt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avbrytActionPerformed(evt);
            }
        });

        arVapen.setText("Vapen");
        arVapen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arVapenActionPerformed(evt);
            }
        });

        arKomm.setText("Kommunikation");
        arKomm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arKommActionPerformed(evt);
            }
        });

        arTeknik.setText("Teknik");
        arTeknik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arTeknikActionPerformed(evt);
            }
        });

        labelFranBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(godkann))
                    .addComponent(jLabel1))
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(arVapen)
                        .addGap(46, 46, 46)
                        .addComponent(arKomm))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(labelFranBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(utrustningNamn, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(avbryt)
                    .addComponent(arTeknik)
                    .addComponent(utrustningDetalj))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arVapen)
                    .addComponent(arKomm)
                    .addComponent(arTeknik))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(utrustningNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(utrustningDetalj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFranBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(godkann)
                    .addComponent(avbryt))
                .addGap(44, 44, 44))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void godkannActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_godkannActionPerformed
        if(Validering.txtFieldHarVarde(utrustningNamn) && Validering.txtFieldHarVarde(utrustningDetalj)){
            try{
                String nextUID = idb.getAutoIncrement("utrustning", "Utrustnings_ID");
                String namn = utrustningNamn.getText();
                String detaljer = utrustningDetalj.getText();
        
                int reply = JOptionPane.showConfirmDialog(null,"Är du säker på att du vill registrera denna utrustning?","Varning!",JOptionPane.YES_NO_OPTION);
            
                if(reply == JOptionPane.YES_OPTION){
                    
                if(arVapen.isSelected()){
                    Validering.txtFieldBegransad10(utrustningDetalj);
                    idb.insert("INSERT INTO vapen VALUES(" + nextUID + ",'" + detaljer + "')");
                }
                else if(arKomm.isSelected()){
                    Validering.txtFieldBegransad20(utrustningDetalj);
                    idb.insert("INSERT INTO kommunikation VALUES(" + nextUID + ",'" + detaljer + "')");
                }
                else if(arTeknik.isSelected()){
                    Validering.txtFieldBegransad20(utrustningDetalj);
                    idb.insert("INSERT INTO teknik VALUES(" + nextUID + ",'" + detaljer + "')");
                }
                idb.insert("INSERT INTO utrustning VALUES(" + nextUID + ",'" + namn + "')");
                JOptionPane.showMessageDialog(null, "Utrustningen har registrerats!");
            }
        
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Något gick fel");
        }
        }
    }//GEN-LAST:event_godkannActionPerformed

    private void avbrytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avbrytActionPerformed
        agentMeny = new AgentMeny(idb, id);
        agentMeny.setVisible(true);
        dispose();
    }//GEN-LAST:event_avbrytActionPerformed

    private void arVapenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arVapenActionPerformed
        if(arVapen.isSelected()){
            arTeknik.setEnabled(false);
            arKomm.setEnabled(false);
            utrustningDetalj.setVisible(true);
            labelFranBox.setText("Ange vapnets kaliber");
        }
        else{
            arTeknik.setEnabled(true);
            arKomm.setEnabled(true);
            utrustningDetalj.setVisible(false);
            labelFranBox.setText("");
        }
    }//GEN-LAST:event_arVapenActionPerformed

    private void arKommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arKommActionPerformed
        if(arKomm.isSelected()){
            arTeknik.setEnabled(false);
            arVapen.setEnabled(false);
            utrustningDetalj.setVisible(true);
            labelFranBox.setText("Ange överföringsteknik");
        }
        else{
            arTeknik.setEnabled(true);
            arVapen.setEnabled(true);
            utrustningDetalj.setVisible(false);
            labelFranBox.setText("");
        }
    }//GEN-LAST:event_arKommActionPerformed

    private void arTeknikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arTeknikActionPerformed
        if(arTeknik.isSelected()){
            arVapen.setEnabled(false);
            arKomm.setEnabled(false);
            utrustningDetalj.setVisible(true);
            labelFranBox.setText("Ange teknikens kraftkälla");
        }
        else{
            arVapen.setEnabled(true);
            arKomm.setEnabled(true);
            utrustningDetalj.setVisible(false);
            labelFranBox.setText("");
        }
    }//GEN-LAST:event_arTeknikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistreraUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistreraUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistreraUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistreraUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistreraUtrustning(idb, id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox arKomm;
    private javax.swing.JCheckBox arTeknik;
    private javax.swing.JCheckBox arVapen;
    private javax.swing.JButton avbryt;
    private javax.swing.JButton godkann;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelFranBox;
    private javax.swing.JTextField utrustningDetalj;
    private javax.swing.JTextField utrustningNamn;
    // End of variables declaration//GEN-END:variables
}
