/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib.application;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author mariaforsberg
 */
public class TaBortAgent extends javax.swing.JFrame {
    
    private static InfDB idb;
    private static String id;
    private ArrayList<String> agentID;

    /**
     * Creates new form AndraKontorsChef
     */
    public TaBortAgent(InfDB idb, String id) {
        initComponents();
        this.idb = idb;
        this.id = id;
        txtAgentNamn.setEditable(false);
        try{
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
            
            agentID = idb.fetchColumn("SELECT Agent_ID FROM Agent ORDER BY Agent_ID ASC");
            agentID.forEach(aid ->  {
                boxValjAgent.addItem(aid);
            });
            
        
        
        
        
        }
        catch(InfException e){
        JOptionPane.showMessageDialog(null, "Något gick fel");
        System.out.println(e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        boxValjAgent = new javax.swing.JComboBox<>();
        txtAgentNamn = new javax.swing.JTextField();
        lblMIB = new javax.swing.JLabel();
        goBack = new javax.swing.JLabel();
        taBortKnapp = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Välj den agent du vill ta bort:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        boxValjAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxValjAgentActionPerformed(evt);
            }
        });
        getContentPane().add(boxValjAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 190, -1));
        getContentPane().add(txtAgentNamn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 190, -1));

        lblMIB.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblMIB.setForeground(new java.awt.Color(255, 255, 255));
        lblMIB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMIB.setText("Ta bort agent från systemet");
        lblMIB.setToolTipText("");
        getContentPane().add(lblMIB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 740, -1));

        goBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/GoBack.png"))); // NOI18N
        goBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackMouseClicked(evt);
            }
        });
        getContentPane().add(goBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        taBortKnapp.setBackground(new java.awt.Color(0, 0, 0));
        taBortKnapp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));
        taBortKnapp.setForeground(new java.awt.Color(102, 153, 255));
        taBortKnapp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        taBortKnapp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taBortKnappMouseClicked(evt);
            }
        });
        taBortKnapp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/accept.png"))); // NOI18N
        taBortKnapp.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 20, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 153, 255));
        jLabel11.setText("Ta bort");
        taBortKnapp.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 70, 30));

        getContentPane().add(taBortKnapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 110, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/spaceBlue.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boxValjAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxValjAgentActionPerformed
        try{
        String id = (String)boxValjAgent.getSelectedItem();
        String hamtaNamn = "SELECT Namn FROM Agent WHERE Agent_ID=" + id;
        String namnFraga = idb.fetchSingle(hamtaNamn);
        txtAgentNamn.setText(namnFraga);}
        catch(InfException e){
        System.out.println(e);
        }
    }//GEN-LAST:event_boxValjAgentActionPerformed

    private void goBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackMouseClicked
        new AdminHanteraAgent(idb, id).setVisible(true);
        dispose();
    }//GEN-LAST:event_goBackMouseClicked

    private void taBortKnappMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taBortKnappMouseClicked
        int valdAgent = Integer.parseInt((String)boxValjAgent.getSelectedItem());
        
        try{       
        
        int svar = JOptionPane.showConfirmDialog(null, "Är du säker på att du vill radera denna agent från systemet? \n"
                + "Åtgärden går inte att ångra.", "Obs!", JOptionPane.YES_NO_OPTION);
        
        if(svar == JOptionPane.YES_OPTION){
            idb.delete("DELETE FROM Innehar_Fordon WHERE Agent_ID=" + valdAgent);
            idb.delete("DELETE FROM Innehar_Utrustning WHERE Agent_ID=" + valdAgent);
            idb.delete("DELETE FROM Kontorschef WHERE Agent_ID =" + valdAgent);
            idb.delete("DELETE FROM Omradeschef WHERE Agent_ID =" + valdAgent);
            idb.delete("DELETE FROM Faltagent WHERE Agent_ID =" + valdAgent);
            idb.delete("DELETE FROM Alien WHERE Ansvarig_Agent =" + valdAgent);
            idb.delete("DELETE FROM Agent WHERE Agent_ID=" + valdAgent);
            JOptionPane.showMessageDialog(null, "Agenten är nu borttagen ur systemet");
            
        }
        
        }
        
        catch(InfException e){
        System.out.println(e);
        }
    }//GEN-LAST:event_taBortKnappMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaBortAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaBortAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaBortAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaBortAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaBortAgent(idb, id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxValjAgent;
    private javax.swing.JLabel goBack;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblMIB;
    private javax.swing.JPanel taBortKnapp;
    private javax.swing.JTextField txtAgentNamn;
    // End of variables declaration//GEN-END:variables
}
