/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib.application;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author mathildabernebyhaeffner
 */
public class TaBortUtrustning extends javax.swing.JFrame {

    private static InfDB idb;
    private static String id;
    private AdminUtrustningHantera hanteraUtrustning;
    /**
     * Creates new form TaBortUtrustning
     */
    public TaBortUtrustning(InfDB idb, String id) {
        initComponents();
        this.idb = idb;
        this.id = id;

        try {
            //Hämtar alla utrustnings-ID:n från databasen och sorterar i stigande ordning
            ArrayList<String> utrustning = idb.fetchColumn("SELECT Utrustnings_ID FROM Utrustning ORDER BY Utrustnings_ID ASC");
            
            //En for each loop för att lista alla id-nummer i en drop-down-meny
            for (String nuvarandeUtrustning : utrustning) {
                cmbUtrustning.addItem(nuvarandeUtrustning);
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cmbUtrustning = new javax.swing.JComboBox<>();
        goBack = new javax.swing.JLabel();
        TabortKnapp = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblMIB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 20, 20));

        getContentPane().add(cmbUtrustning, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 137, -1));

        goBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/GoBack.png"))); // NOI18N
        goBack.setToolTipText("");
        goBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                goBackMouseReleased(evt);
            }
        });
        getContentPane().add(goBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        TabortKnapp.setBackground(new java.awt.Color(0, 0, 0));
        TabortKnapp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));
        TabortKnapp.setForeground(new java.awt.Color(102, 153, 255));
        TabortKnapp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabortKnapp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TabortKnappMouseReleased(evt);
            }
        });
        TabortKnapp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/accept.png"))); // NOI18N
        TabortKnapp.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 20, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 153, 255));
        jLabel4.setText("Ta bort");
        TabortKnapp.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 70, 30));

        getContentPane().add(TabortKnapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 110, 30));

        lblMIB.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblMIB.setForeground(new java.awt.Color(255, 255, 255));
        lblMIB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMIB.setText("Ta bort Utrustning");
        lblMIB.setToolTipText("");
        getContentPane().add(lblMIB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 740, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/spaceBlue.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TabortKnappMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabortKnappMouseReleased
        String valdUtrustning = cmbUtrustning.getSelectedItem().toString();

        try {
            //Hämtar ut kolumnen utrustning-ID från alla tabeller i databasen där utrustnings-ID förekommer
            ArrayList<String> innehar_utrustning = idb.fetchColumn("SELECT Utrustnings_ID FROM Innehar_Utrustning");
            ArrayList<String> kommunikation = idb.fetchColumn("SELECT Utrustnings_ID FROM Kommunikation");
            ArrayList<String> teknik = idb.fetchColumn("SELECT Utrustnings_ID FROM Teknik");
            ArrayList<String> vapen = idb.fetchColumn("SELECT Utrustnings_ID FROM Vapen");

            
            
            String utrNamn = idb.fetchSingle("SELECT Benamning FROM Utrustning WHERE Utrustnings_ID=" + valdUtrustning);

            //Kod som framkallar en varningsruta när användaren försöker ta bort utrustning
            int reply = JOptionPane.showConfirmDialog(null, "Är du säker på att du vill ta bort Utrustning vid namn '" + utrNamn + "'", "Varning!", JOptionPane.YES_NO_OPTION);
            
            /*Om användaren bekräftar borttagningen, ser nedanstående kod till att den valda utrustningen 
            försvinner i alla tabeller genom for each loopar, med if-satser vars syfte är att jämföra valt utrustnings-ID
            med utrustnings-ID:n i databastabellerna. Borttagning sker vid hittad matchning 
            */
            if (reply == JOptionPane.YES_OPTION) {
                idb.delete("DELETE FROM Utrustning WHERE Utrustnings_ID =" + valdUtrustning);
                
            for (String i : innehar_utrustning) {
                if (i.equals(valdUtrustning)) {
                    idb.delete("DELETE FROM Innehar_Utrustning WHERE Utrustnings_ID=" + valdUtrustning);
                }
            }
            for (String j : kommunikation) {
                if (j.equals(valdUtrustning)) {
                    idb.delete("DELETE FROM Kommunikation WHERE Utrustnings_ID=" + valdUtrustning);
                }
            }
            for (String k : teknik) {
                if (k.equals(valdUtrustning)) {
                    idb.delete("DELETE FROM Teknik WHERE Utrustnings_ID=" + valdUtrustning);
                }
            }
            for (String k : vapen) {
                if (k.equals(valdUtrustning)) {
                    idb.delete("DELETE FROM Vapen WHERE Utrustnings_ID=" + valdUtrustning);
                }
            }
                JOptionPane.showMessageDialog(null, "Utrustning '" + utrNamn + "' borttagen!");
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_TabortKnappMouseReleased

    private void goBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackMouseReleased
        hanteraUtrustning = new AdminUtrustningHantera(idb,id);
        hanteraUtrustning.setVisible(true);
        dispose();
    }//GEN-LAST:event_goBackMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TabortKnapp;
    private javax.swing.JComboBox<String> cmbUtrustning;
    private javax.swing.JLabel goBack;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblMIB;
    // End of variables declaration//GEN-END:variables
}
