/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib.application;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author mariaforsberg
 */
public class TilldelaAdminStatus extends javax.swing.JFrame {
    private ArrayList<String> agentID;
    private static InfDB idb;
    private static String id;
    

    /**
     * Creates new form TilldelaAdminStatus
     */
    public TilldelaAdminStatus(InfDB idb, String id) {
        initComponents();
        this.idb = idb;
        this.id = id;
        
        //Gör så att textrutan inte går att redigera av användaren i gränssnittet
        txtNamn.setEditable(false);
       
        try{ 
            //Hämtar alla agent-ID:n för agenter som ännu inte har adminstatus
            agentID = idb.fetchColumn("SELECT Agent_ID FROM Agent WHERE Administrator='N'");
            
            //En for each loop för att lista alla agent-ID:n i en drop-down-meny
            agentID.forEach(idNr -> {
                boxAgenter.addItem(idNr);
                                    });       
            }
            catch(InfException e){
            JOptionPane.showMessageDialog(null, "Hoppsan! Det gick inte att hämta ID:n. Vänligen försök igen");
            }
        
   } 
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        boxAgenter = new javax.swing.JComboBox<>();
        txtNamn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblMIB = new javax.swing.JLabel();
        goBack = new javax.swing.JLabel();
        godkännKnapp = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boxAgenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAgenterActionPerformed(evt);
            }
        });
        getContentPane().add(boxAgenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 79, -1));
        getContentPane().add(txtNamn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 190, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Välj ID-nummer:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, 20));

        lblMIB.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblMIB.setForeground(new java.awt.Color(255, 255, 255));
        lblMIB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMIB.setText("Tilldela agent administratörsstatus");
        lblMIB.setToolTipText("");
        getContentPane().add(lblMIB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 740, -1));

        goBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/GoBack.png"))); // NOI18N
        goBack.setToolTipText("");
        goBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                goBackMouseReleased(evt);
            }
        });
        getContentPane().add(goBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        godkännKnapp.setBackground(new java.awt.Color(0, 0, 0));
        godkännKnapp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));
        godkännKnapp.setForeground(new java.awt.Color(102, 153, 255));
        godkännKnapp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        godkännKnapp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                godkännKnappMouseReleased(evt);
            }
        });
        godkännKnapp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/accept.png"))); // NOI18N
        godkännKnapp.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 20, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 153, 255));
        jLabel4.setText("Godkänn");
        godkännKnapp.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 70, 30));

        getContentPane().add(godkännKnapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 110, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/spaceBlue.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boxAgenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAgenterActionPerformed
        //Kod som ser till att textrutan i gränssnittet fylls med den valda agentens namn, baserat på agent-ID
        try{
            String idNr = (String)boxAgenter.getSelectedItem();
            String namn = idb.fetchSingle("SELECT Namn FROM Agent WHERE Agent_ID =" + idNr);
            txtNamn.setText(namn);
        }
                catch(InfException e){
                JOptionPane.showMessageDialog(null, "Kunde inte hämta namnet för denna agent. Vänligen försök igen");
                }
    }//GEN-LAST:event_boxAgenterActionPerformed

    private void godkännKnappMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_godkännKnappMouseReleased
        //Uppdaterar berörd agent till administratör när användaren klickar på "godkänn"
        try {
            String idNr = (String)boxAgenter.getSelectedItem();
            idb.update("UPDATE Agent SET Administrator= 'J' WHERE Agent_ID =" + idNr);
            JOptionPane.showMessageDialog(null, "Tilldelningen av administratörsstatus lyckades!");
        } 
        catch (InfException ex) {
                JOptionPane.showMessageDialog(null, "Hoppsan! Det gick tyvärr inte att tilldela administratörsstatus. Vänligen försök igen");
            }
    }//GEN-LAST:event_godkännKnappMouseReleased

    private void goBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackMouseReleased
        new AdminHanteraAgent(idb, id).setVisible(true);
        dispose();
    }//GEN-LAST:event_goBackMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxAgenter;
    private javax.swing.JLabel goBack;
    private javax.swing.JPanel godkännKnapp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblMIB;
    private javax.swing.JTextField txtNamn;
    // End of variables declaration//GEN-END:variables
}
